# Generated by Django 6.0.6 on 2026-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('available_qty', models.IntegerField(default=0)),
                ('minimum_qty', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
