# Generated by Django 6.0.6 on 2026-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0002_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance'), ('IT', 'IT'), ('Admin', 'Admin'), ('Operations', 'Operations')], default='HR', max_length=20),
        ),
    ]
